### ISSUE TITLE
Problems installing Rosetta in Mac OS Big Sur (11.7.2)

### ISSUE THREAD

**Issue by lucasalbertins** [opencaesar/oml-rosetta#30]
Hello,

I tried to install Rosetta 1.4 on my Mac OS Big Sur, but when I try to run the executable it says "“Rosetta.app” is damaged and can’t be opened. You should move it to the Bin". My mac book is intel, so I am using the [rosetta-1.4.0-macosx.cocoa.x86_64.zip] file. Do you know what may be happening?

**Comment by melaasar** [comment]
Yes there is a note in the README about this that reads:

Note: on MacOS, the application is currently NOT signed, so you may get an error like the app is damaged and can't be opened. To get around that, you can run the following command in terminal:
```
xattr -cr /path/to/Rosetta.app
```
